apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Cilium: The eBPF-based Networking, Security, and Observability layer.
# Replaces kube-proxy and provides a highly performant Service Mesh.

helmCharts:
  - name: cilium
    repo: https://helm.cilium.io/
    version: 1.15.5
    releaseName: cilium
    namespace: kube-system
    valuesInline:
      kubeProxyReplacement: true
      hubble:
        relay:
          enabled: true
        ui:
          enabled: true
