apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: cloud-native-build-pipeline
spec:
  workspaces:
    - name: shared-workspace
  tasks:
    - name: fetch-repository
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-workspace
      params:
        - name: url
          value: "https://github.com/ygtersln/cloud-native-devops-blueprint.git"

    - name: security-scan
      taskRef:
        name: trivy-scan
      runAfter:
        - fetch-repository
      workspaces:
        - name: source
          workspace: shared-workspace

    - name: build-and-push
      taskRef:
        name: buildah
      runAfter:
        - security-scan
      workspaces:
        - name: source
          workspace: shared-workspace
      params:
        - name: IMAGE
          value: "ghcr.io/ygtersln/cloud-native-devops-blueprint/api:latest"
