---
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-vault-token
  namespace: cert-manager
  annotations:
    kubernetes.io/service-account.name: cert-manager
type: kubernetes.io/service-account-token
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: vault-issuer
spec:
  vault:
    server: http://openbao-vault-0.openbao.svc:8200
    path: pki/sign/blueprint-dot-local
    auth:
      kubernetes:
        mountPath: /v1/auth/kubernetes
        role: cert-manager
        secretRef:
          name: cert-manager-vault-token
          key: token
